#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Simple\App\Runner\ConsoleApplicationRunner;

$consoleRunner = new ConsoleApplicationRunner();

// Run application:
$consoleRunner->run();
