#!/usr/bin/env php
<?php

declare(strict_types=1);

use Simple\App\ApplicationConsoleRunner;

define('YII_ENV', getenv('env') ?? 'production');

require_once 'vendor/autoload.php';

$runnerConsole = new ApplicationConsoleRunner();

// Run application:
$runnerConsole->run();
